name: epgdiyp

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Run epgdiyp.php
        run: php epgdiyp.php

      - name: Verify file existence
        run: |
          if [ ! -f epgdiyp.json ]; then
              echo "错误：epgdiyp.json 未生成"
              exit 1
          fi

      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: zzq1234567890/epg
          token: ${{ secrets.GITHUB_TOKEN }}
          path: epg

      - name: Overwrite target file
        run: |
          cp -f epgdiyp.json epg/epgdiyp.json
          ls -l epg/epgdiyp.json  # 验证复制结果

      - name: Commit and push
        working-directory: epg
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --all
          if [ -n "$(git status --porcelain)" ]; then
              now_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
              git commit -m "自动更新时间：$now_time"
              git push origin main
          else
              echo "无实际文件变更，跳过提交"
          fi
