name: Sync files from epgtest2 to epg

on:
  push:
    branches:
      - main  # 或者你希望觸發操作的分支名稱
  pull_request:
    branches:
      - main  # 或者你希望觸發操作的分支名稱

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout epg repository
      uses: actions/checkout@v3  # 檢出 epg 倉庫

    - name: Checkout epgtest2 repository
      uses: actions/checkout@v3
      with:
        repository: zzq1234567890/epgtest2
        token: ${{ secrets.GITHUB_TOKEN }}  # 用來驗證權限，預設的 GitHub token
        path: epgtest2  # 將其檢出到子目錄

    - name: Ensure epg directory exists
      run: |
        mkdir -p zzq1234567890/epg  # 確保 epg 目錄存在

    - name: Copy files from epgtest2 to epg
      run: |
        cp -r ./epgtest2/epg4gtv2.xml zzq1234567890/epg/  # 將檔案從 epgtest2 複製到 epg 目錄

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .  # 添加變更
        git commit -m "Sync files from epgtest2"  # 提交更改
        git push origin main  # 推送到 main 分支
