name: youtubelivetxt

# 每小时执行一次
on:
  schedule:
    - cron: '5 * * * *'  # 每小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  generate_and_upload:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境运行

    steps:
      # 第一步：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 第二步：设置 PHP 7.4 环境
      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      # 第三步：运行 youtubelivetxt.php，生成 youtubelive.txt
      - name: Run youtubelivetxt.php
        run: |
          php youtubelivetxt.php  # 运行生成 youtubelive.txt 的 PHP 脚本

      # 第四步：上传文件到 epgtest2 仓库
      - name: Upload youtubelive.txt to epgtest2
        uses: actions/upload-artifact@v4
        with:
          name: youtubelive.txt
          path: youtubelive.txt

      # 第五步：下载到目标仓库并覆盖文件
      - name: Checkout tvepg repository
        uses: actions/checkout@v4
        with:
          repository: zzq1234567890/epg  # 目标仓库
          token: ${{ secrets.GITHUB_TOKEN }}
          path: epg  # 克隆到本地的路径

      # 第六步：检查 youtubelive.txt 是否存在并被修改
      - name: Check if youtubelive.txt exists and is modified
        run: |
          if [ ! -f youtubelive.txt ]; then
            echo "youtubelive.txt does not exist."
            exit 1
          fi
          if ! diff epg/youtubelive.txt youtubelive.txt >/dev/null; then
            echo "File is modified"
            echo "modified=true" >> $GITHUB_ENV
          else
            echo "No changes detected"
            exit 0
          fi

      # 第七步：提交并推送更改
      - name: Commit and push changes
        if: env.modified == 'true'  # 只有在文件修改时才执行
        run: |
          cd epg
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add youtubelive.txt
          now_time=$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')
          git commit -m "更新时间：$now_time"
          git push origin main || echo "推送到GitHub失败"
          
